# Generated by Django 4.0.5 on 2022-10-14 21:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VVZSubjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('credits', models.IntegerField()),
                ('vvz_id', models.IntegerField()),
                ('lesson_number', models.CharField(max_length=256)),
                ('semester', models.BooleanField()),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserSubjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('credits', models.IntegerField()),
                ('category', models.CharField(max_length=256)),
                ('semester', models.BooleanField()),
                ('year', models.IntegerField()),
                ('grade', models.FloatField()),
                ('count_grade', models.BooleanField()),
                ('count_credits', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to=settings.AUTH_USER_MODEL)),
                ('vvz_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_subjects', to='app.vvzsubjects')),
            ],
        ),
    ]
