# Generated by Django 4.1.2 on 2022-10-15 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubjects',
            name='count_credits',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='usersubjects',
            name='count_grade',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='usersubjects',
            name='grade',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='usersubjects',
            name='vvz_subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_subjects', to='app.vvzsubjects'),
        ),
    ]
