# Generated by Django 4.0.5 on 2022-10-15 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_usersubjects_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vvzsubjects',
            name='category',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
