# Generated by Django 4.1.2 on 2022-10-22 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_count_credits_usersubjects_planned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vvzsubjects',
            name='vvz_id',
            field=models.IntegerField(unique=True),
        ),
    ]
