# Generated by Django 4.1.2 on 2022-10-22 16:15

from django.db import migrations
from app import util

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_vvzsubjects_vvz_id'),
    ]

    operations = [
        migrations.RunPython(util.fill_database)
    ]
